version: '3.8'
services:
    web:
        build: .
        container_name: apache_server
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./config/000-default.conf:/etc/apache2/sites-available/000-default.conf
            - ./config/php.ini:/etc/php/8.2/apache2/conf.d/php.ini
        environment:
            - APACHE_LOG_DIR=/var/log/apache2
        restart: always
        networks:
            - app-network
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql8
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: nhimgau
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbuser
        volumes:
            - ./database/mysql:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge